org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Gradle
maven_group=cc.dvitski
loom_version=1.12-SNAPSHOT

# Minecraft
minecraft_version=1.21.10

# Mod Properties
mod_id=silana
mod_version=1.0.1

# Versions

loader_version=0.17.3
kotlin_version=2.2.21
fabric_kotlin_version=1.13.7

fabric_version=0.138.0+1.21.10
